### ISSUE TITLE
Missing the file: reprap.html

### ISSUE THREAD

**Issue by MS1987** [dc42/DuetWiFiServer#2]
Mr dc42,
  I come again.
  Yesterday I could not visit the web ui because I had not load the ".html" file to the file system. But I found there's no "reprap.html" in your project. 

`void fsHandler()
{
  String path = server.uri();
  if (path.endsWith("/"))
 {
    path += F("reprap.htm");            // default to reprap.htm as the index page
  }
  bool addedGz = false;
  File dataFile = SPIFFS.open(path, "r");`

**Comment by dc42** [comment]
The HTML file set is a separate project, DuetWebControl, maintained by Chrstian Hammacher at https://github.com/chrishamm/DuetWebControl.
