### ISSUE TITLE
How to upload the WebControl files?

### ISSUE THREAD

**Issue by MS1987** [dc42/DuetWiFiServer#3]
Mr dc42,
    Sorry to trouble you again!
    According to your guide, I use the webControl files at : https://github.com/dc42/DuetWebControl. And I use the arduino tools(esp8266fs.jar) to upload the "DuetWebControl.bin" file, but there was an issue as followed:

> "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 921600, 4M (3M SPIFFS), ck, Disabled, None"
> ......
> [SPIFFS] data   : E:\RepRapWiFi\data
> [SPIFFS] size   : 3052
> [SPIFFS] page   : 256
> [SPIFFS] block  : 8192
> /DuetWebControl.bin
> 
> SPIFFS_write error(-10001): File system is full.

It hinted that my file system is full ,but I had configure the spiffs to occupy 3M size. And I can upload the small size file successfully.

So I suspect it's not the correct way to upload.
I wonder how to upload the "DuetWebControl.bin" file.
Thank you very much!

**Comment by dc42** [comment]
We upload DuetWiFi.bin via the Duet WiFi. During prototyping, we used ESPTool to upload it. The Arduino IDE has an option to do this. If you are using our DuetWebControl.bin then obviously your ESP8266 needs to be a variant with 4Mb flash memory.

PS - in case you hadn't realised, DuetWebControl.bin is a SPIFFS image containing all the web files.

**Comment by MS1987** [comment]
Thank you, sir!
It's the problem of the upload tool I used.
Now I use the ESP_DOWNLOAD_TOOL_V2.4.exe tool and upload the *.bin file the 0x100000 successfully! The web ui has display. 
Thanks.
